RISC-V: Add support for riscv kexec/kdump on kexec-tools
This patch adds support for loading the ELF kernel image. It parses
the current/provided device tree to determine the system's memory
layout, and /proc/iomem for the various kernel segments.

Tested on Qemu's rv64 virt machine and SoC of T-Head RISC-V Xuantie
910 CPU.

Now, some history: The first stab at supporting kexec-tools on RISC-V
was done by Nick Kossifidis. The initial patch has since then had a
number of improvements/fixes by other authors. Given, this is the
first commit for RISC-V, carrying the fixes/changes commits in the
upstream tree does not really add anything (bisectability).

Instead all the fixes that were applied to Nick's first commit is
outlined below:

Yixun Lan, and Xianting Tian:
  * Fixed a failure to fail to find free memory area for dtb load when
    using initrd image [1].
  * Fixed memory range size calculation in
    kexec/arch/riscv/crashdump-riscv.c:85

Simon Horman:
  * workflow: Add riscv64

    Add riscv64 to matrix of build architectures.
  * RISC-V: distribute purgatory/riscv/Makefile

    Include purgatory/riscv/Makefile in distribution tarball.

    Local patch as it is planned to suggest this as a fix for the
    patch that introduced this problem. [2]

Song Shuai:
  * RISC-V: Fix the undeclared ‘EM_RISCV’ build failure

    Use local `elf.h` instead of `linux/elf.h` to fix this build
    error:

    ```
    kexec/arch/riscv/crashdump-riscv.c:17:13: error: ‘EM_RISCV’ undeclared here (not in a function); did you mean ‘EM_CRIS’?
      .machine = EM_RISCV,
                 ^~~~~~~~
                 EM_CRIS
    ```

  * RISC-V: Correct the usage of command line option

    RISC-V process OPT_CMDLINE with the "command-line" partten, but
    the riscv_opts_usage shows the "cmdline" option. So correct the
    usage's output.

  * RISC-V: Use linux,usable-memory-range for crash kernel

    Now we use "memeory::linux,usable-memory" to indicate the
    available memory for the crash kernel.

    While booting with UEFI, the crash kernel would use efi.memmap to
    re-populate memblock and then first kernel's memory would be
    corrputed. Consequently, the /proc/vmcore file failed to create in
    my local test.

    And according to "chosen" dtschema [3], the available memory for
    the crash kernel should be held via
    "chosen::linux,usable-memory-range" property which will re-cap
    memblock even after UEFI's re-population.

  * RISC-V: Get memory ranges from iomem

    When booting with UEFI, Linux marks the Runtime Code/Data memory
    as no-map and then exports it to "Reserved" iomem_resource.

    Kexc-tools uses dtb_get_memory_ranges() function to get memory
    ranges via parsing dtb, but it can't see the Reserved EFI Runtime
    memory. That would corrupt EFI Runtime memory and fail the kexeced
    kernel to deal EFI stuff.

    In my test, the kexeced kernel warned "efi: System table signature
    incorrect!" and then paniced at efi_call_rts() due to the null
    efi.runtime.

    So we should use /proc/iomem to get memory ranges.

Björn Töpel:
  * Massaged this commit message!
  * Fixed up the build, by adding missing RV stub.
  * RISC-V: Only cap the upper/end usable memory window

    When loading the initrd in the kexec_load flow, memory for the
    segments are searched from end to start. Only the max_usable
    should be capped, after a successful initrd addtion.

    Currently min/max usable is set to the same value, making it
    impossible from subsequent segment allocations to success.

  * RISC-V: Make get_memory_ranges() properly exclude "Reserved"
    regions

    The get_memory_ranges() did not exclude "Reserved" regions from
    "System RAM" regions. It simply added "Reserved" as IOMEM, and
    IOMEM is not considered when looking for holes to place kexec
    segments.

    Instead, do a two pass of the /proc/iomem file. First pass, adds
    all the "System RAM" memory, and the second pass removes all
    intersecting "Reserved" regions.

[1] https://lore.kernel.org/linux-riscv/CALecT5gQWn0PRO4Q24b6qkrfVE5OxsCp65TuhWTb30ceK_OJ0A@mail.gmail.com/
[2] https://lore.kernel.org/kexec/20221020031548.47587-1-xianting.tian@linux.alibaba.com/
[3] https://github.com/devicetree-org/dt-schema/blob/main/dtschema/schemas/chosen.yaml

Tested-by: Yixun Lan <yixun.lan@gmail.com>
Co-developed-by: Xianting Tian <xianting.tian@linux.alibaba.com>
Co-developed-by: Yixun Lan <yixun.lan@gmail.com>
Signed-off-by: Nick Kossifidis <mick@ics.forth.gr>
Signed-off-by: Song Shuai <songshuaishuai@tinylab.org>
Signed-off-by: Björn Töpel <bjorn@rivosinc.com>
Signed-off-by: Simon Horman <horms@kernel.org>