kexec-tools: Fix unused return value warnings
This patch fixes following warning:

kexec/firmware_memmap.c: In function ‘parse_numeric_sysfs’:
kexec/firmware_memmap.c:70: error: ignoring return value of ‘fgets’, declared
with attribute warn_unused_result
kexec/firmware_memmap.c: In function ‘parse_string_sysfs’:
kexec/firmware_memmap.c:103: error: ignoring return value of ‘fgets’, declared
with attribute warn_unused_result

Difference between v1 and v2: Less indentation.

Signed-off-by: Ameya Palande <ameya.palande@nokia.com>
Signed-off-by: Simon Horman <horms@verge.net.au>