fix ppc64 kexec tools build failure when DEBUG is enabled.
When DEBUG [ in kexec/arch/ppc64/crashdump-ppc64.c ] is defined, kexec
tools for ppc64 fails with following error

kexec/arch/ppc64/crashdump-ppc64.c: In function get_crash_memory_ranges':
kexec/arch/ppc64/crashdump-ppc64.c:235: error: 'redeclaration of i' with no linkage
kexec/arch/ppc64/crashdump-ppc64.c:109: error: previous declaration of 'i' was here

Here is a patch to fix the above error.

Thanks
-Sachin

Signed-off-by : Sachin Sant <sachinp@in.ibm.com>
Signed-off-by : Simon Horman <horms@verge.net.au>