kexec-tools : fix compile time error on x86-64
On x86_64 machines running kernels having relocatale kernel patches
compilation of kexec tools fails with following error.

kexec/arch/i386/kexec-multiboot-x86.c:347: warning: implicit declaration of function ‘_AC’
kexec/arch/i386/kexec-multiboot-x86.c:347: error: ‘UL’ undeclared (first use in this function)
kexec/arch/i386/kexec-multiboot-x86.c:347: error: (Each undeclared identifier is reported only once
kexec/arch/i386/kexec-multiboot-x86.c:347: error: for each function it appears in.)

The error is bacause of the use of PAGE_SIZE macro in the above file. On
x86_64 arch PAGE_SIZE is defined as

#define PAGE_SIZE       (_AC(1,UL) << PAGE_SHIFT)

and hence fails to find definitation for _AC().

The correct way to fix this is to use getpagesize() function instead of
PAGE_SIZE macro.

Signed-off-by : Sachin Sant <sachinp@in.ibm.com>
Acked-by: Vivek Goyal <vgoyal@in.ibm.com>
Signed-off-by : Simon Horman <horms@verge.net.au>